//RealizarConfiguracionesParaQueElMicroservicioSeEjecuteYAgregarCredeciales

spring.application.name=auth
server.port=8080

//EstoEsDeJPA
spring.datasource.url=jdbc:postgresql://localhost:5433/bionodo
spring.datasource.username=postgres
spring.datasource.password=Edwin1020
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= update

