//RealizarConfiguracionesParaQueElMicroservicioSeEjecuteYAgregarCredeciales

spring.application.name=unlock
server.port=8082

//EstoEsDeJPA
spring.datasource.url=jdbc:postgresql://localhost:5432/bionodo
spring.datasource.username=postgres
spring.datasource.password=mauro090204
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= update
