//RealizarConfiguracionesParaQueElMicroservicioSeEjecuteYAgregarCredeciales

spring.application.name=auth
server.port=8082

//EstoEsDeJPA
spring.datasource.url=jdbc:postgresql://localhost:5432/bionodo
spring.datasource.username=postgres
spring.datasource.password=edwin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto= update
file.upload-dir=C:/BIONODO/Bionodo/Catalogo_Service/uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
services.catalogo.url=http://localhost:8080